### ISSUE TITLE
Version 1.1 on npm doesn't have re-generated files

### ISSUE THREAD

**Issue by MarcusP-P** [gksander/CIE-ColorConverter#1]
It looks like the version of this on NPM doesn't have the re-generated index.js/browser.js

It appears that they are missing the new functions.

**Comment by gksander** [comment]
Hi @MarcusP-P. Thanks for reaching out! Not going to lie... I totally forgot I had created this library!

This library is actually pretty neat - and I'm pleasantly surprised that I had written some tests for it years ago when I created it!

I actually just did a major version bump to 2.0.0, due to some large updates I felt compelled to make:

- Changed the main default export to a named export, so import the converter with `import { ColorConverter } from ....`.
- Removed the dependency on `mathjs`, which slims the bundle down tremendously. (That was only being used for a few bits of matrix math, which I pulled out manually.)
- Updated the README accordingly.

If you get a chance to try 2.0.1, let me know how it goes! I'd be happy to hear how it works, and help fix anything that might be broken. I'm also curious what you're using this library for! (A CIE color converter is a pretty niche thing, so I'm curious what has you in the trenches of color space conversions 😅 )

**Comment by gksander** [comment]
I haven't touched this library in three years - but it's in pretty good shape actually! It even has a full test suite. I think I'm going to take some time today to make some improvements to this, including:

- A better `README.md` with instructions on how to contribute.
- I'm going to remove the `mathjs` dependency. It's bulkier than what's needed. All that's needed for the math here is some matrix multiplication/inversion, and we could ship a much slimmer bundle.
- Update the build/release pipeline.

**Comment by MarcusP-P** [comment]
Hi @gksander,

Thanks for that. version 2.0.1 works perfectly, and using your own Matrix functions reduced the size of the JavaScript, so thank you for that!

I'm playing around with simulating colourblind vision. None of the current simulators seem to quite get it right for me, and a couple of the approaches that I've seen involve going from sRGB to either Luv or xyY. I initially rolled my own partial implementation as well, but then I came across your module, and thought that it was probably easier to go that route. :)

Thanks for your work on the module, and saving me writing the rest of the calculations!

Thanks,
Marcus
